#165412874 user login local
andela/ninjas-ah-frontend pull request #10
Opened 2019-06-28 11:07 UTC by sengayire

#### What does this PR do?
create a Login component that will allow a user to login to Authors Haven
#### Description of Task to be completed?
- create a reusable form component and connect react app with backend app to validate user before logging in

#### How should this be manually tested?
- clone the repo and run npm start to open the app in browser
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
#165412874 (https://www.pivotaltracker.com/story/show/165412874)

#### Screenshots (if appropriate)
<img width="700" alt="Screen Shot 2019-06-28 at 13 06 57" src="https://user-images.githubusercontent.com/22425325/60338236-b5303600-99a5-11e9-86a9-c63700a47499.png">

#### Questions:
- N/A

2019-06-29 06:53 UTC, kagaramag requested changes

2019-06-29 06:53 UTC, djallas commented on src/components/Signup/Signup.scss
> +// }
remove comments

2019-06-30 00:18 UTC, luc-tuyishime commented on src/components/Login/Login.js
> +// import Layout from '../Layout';
Remove comment

2019-07-02 16:59 UTC, sengayire commented
@e-liyai this is the PR for local login

2019-07-03 10:52 UTC, luc-tuyishime commented on src/__test__/__Components__/user/__snapshots__/Login.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Do we really need this snapshot file?

2019-07-03 10:52 UTC, luc-tuyishime commented on src/__test__/__reducers__/userReducer.test.js
> +    const payload = {
It will be better if we have this payload defined in the mock user file to have proper and clean code.

2019-07-03 14:10 UTC, sengayire commented on src/__test__/__Components__/user/__snapshots__/Login.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
no let remove it

2019-07-03 14:10 UTC, sengayire commented on src/__test__/__Components__/user/__snapshots__/Login.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Done

2019-07-08 12:03 UTC, e-liyai requested changes

2019-07-08 12:03 UTC, e-liyai commented on src/components/Login/Login.scss
> +// input {
remove comments

2019-07-10 08:03 UTC, luc-tuyishime commented on src/__test__/__Components__/user/__snapshots__/Login.test.js.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Thank you

2019-07-10 10:58 UTC, luc-tuyishime approved these changes

2019-07-10 11:02 UTC, kagaramag approved these changes

2019-07-10 11:26 UTC, e-liyai approved these changes

2019-07-10 11:26 UTC, merged